#!/bin/zsh
set -eux -o pipefail

base=${0:a:h}
cd $base

venv=$base/.venv

if [[ ! -d $venv ]]; then

    if ! which python3.9 virtualenv; then
        sudo apt-get install -y python3.9 python3-env
    fi

    virtualenv --python python3.9 $venv
fi

export VIRTUAL_ENV=$venv
path=($venv/bin $path)

pip install --upgrade pip pip-tools
pip-sync
