from ltstatus.monitors._bluetooth import Monitor as bluetooth
from ltstatus.monitors._cpu import Monitor as cpu
from ltstatus.monitors._datetime import Monitor as datetime
from ltstatus.monitors._diskspace_alerts import Monitor as diskspace_alerts
from ltstatus.monitors._dropbox import Monitor as dropbox
from ltstatus.monitors._nvidia import Monitor as nvidia
from ltstatus.monitors._process_alerts import Monitor as process_alerts
from ltstatus.monitors._redshift import Monitor as redshift
from ltstatus.monitors._sound import Monitor as sound
from ltstatus.monitors._spotify import Monitor as spotify
